### ISSUE TITLE
travis ci: Swift does not support the SDK 'MacOSX10.14.sdk'

### ISSUE THREAD

**Issue by kelvin13** [kylef/swiftenv#160]
I’m trying to use the latest development snapshot of Swift on Travis CI, but i’m running into this versioning issue:

```
error: manifest parse error(s):
<unknown>:0: error: Swift does not support the SDK 'MacOSX10.14.sdk'
```

The [travis script](https://travis-ci.org/kelvin13/png/jobs/553535756/config) i was using is:
```yaml
language: generic
matrix:
  include:
  - os: osx
    osx_image: xcode10.2
    env:
    - JOB="MacOS"
  - os: linux
    env:
    - JOB="Linux"
    dist: trusty
script:
- export SWIFT_VERSION=DEVELOPMENT-SNAPSHOT-2019-07-01-a
- git clone --depth 1 https://github.com/kylef/swiftenv.git ~/.swiftenv
- export SWIFTENV_ROOT="$HOME/.swiftenv"
- export PATH="$SWIFTENV_ROOT/bin:$SWIFTENV_ROOT/shims:$PATH"
- swiftenv install $SWIFT_VERSION
- swiftenv rehash
- swift run -c release tests
```

Is there a way to get dev nightlies working on Travis?
