### ISSUE TITLE
Travis CI - We don't have build instructions for 5.2.1

### ISSUE THREAD

**Issue by iainsmith** [kylef/swiftenv#169]
Hi @kylef,

I'm just seeing an issue where the installer is failing for 5.2(.1) but working for 5.1 on travis-ci.org

```sh
export SWIFT_VERSION=5.2.1
eval "$(curl -sL https://swiftenv.fuller.li/en/latest/install.sh)" 
> We don't have build instructions for 5.2.1
```

I'm not sure if this is a travis issue or a swiftenv issue. I'll try to dig into it a bit, but if you've got any pointers, it would be much appreciated. Thanks

**Comment by kylef** [comment]
Is that when running against Ubuntu or macOS, and which version of the respective platform are you running against?

**Comment by iainsmith** [comment]
@kylef 

This is the reduced travis config, that works fine for 5.1, but then fails on 5.2/5.2.1.

```yml
language: generic
dist: trusty
osx_image: xcode11.4
os:
  - linux
  - osx
env:
  - SWIFT_VERSION=5.1
install:
  - eval "$(curl -sL https://swiftenv.fuller.li/en/latest/install.sh)"
script:
  - set -o pipefail
  - swift test
```
