### ISSUE TITLE
Can not install 2.2 on Travis

### ISSUE THREAD

**Issue by ilyapuchka** [kylef/swiftenv#27]
Here is my travis.yml file:

```yml
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode7.3

language: generic

install:
- ./.travis/install.sh

script:
- ./.travis/build.sh
```

install.sh:

```bash
eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/02090c7ede5a637b76e6df1710e83cd0bbe7dcdf/swiftenv-install.sh)"
```
Here is the log: http://pastebin.com/BQFHniaa
